repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^(alembic/|scripts/|web/)

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        exclude: ^(alembic/|tests/|scripts/|web/)
        # additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
