services:
  postgres:
    image: postgres:17
    container_name: artificial_u_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: artificial_u_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: artificial_u_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_THREADS=2
      - OLLAMA_NUM_GPU=0 # Disable GPU
      - OLLAMA_MODEL_PATH=/root/.ollama/models
    mem_limit: "1g"
    cpus: 2.0

volumes:
  postgres_data:
  ollama_data:
