/**
 * Terms of Service content.
 *
 * This is the English (default) copy. If a locale-specific version is needed
 * in the future, create `tos_es.ts`, `tos_fr.ts`, etc. with the same shape,
 * then import the right one in `pages/AboutTerms.tsx` based on the current
 * locale (e.g. via `useLocale()` from `../i18n`).
 */

export type TosSection = {
  heading: string
  /** Each string renders as its own paragraph. Supports inline HTML links. */
  paragraphs: string[]
  /** Optional bulleted list items that follow the paragraphs. */
  items?: string[]
}

export type TosContent = {
  title: string
  lastUpdated: string
  /** Introductory paragraph shown before the first section. */
  intro: string
  sections: TosSection[]
  /** Optional closing note shown after all sections. */
  closing?: string
}

export const tos: TosContent = {
  title: 'Terms of Service',
  lastUpdated: 'March 28, 2026',
  intro:
    'ArtificialU is an educational entertainment platform. We use AI to generate imaginary professors, courses, and lectures. This is not a real university. Nothing here is accredited. Don\u2019t cite our lectures in your dissertation.\n\nBy using this service, you accept these terms. If you don\u2019t, please close this tab.',
  sections: [
    {
      heading: 'What This Is (and Isn\u2019t)',
      paragraphs: [
        'This is: an experiment in AI-generated educational content, and entertainment and creative exploration.',
      ],
      items: [
        'Not an accredited educational institution',
        'Not a substitute for actual university courses',
        'Not a source of verified, peer-reviewed information',
        'Not professional advice of any kind',
      ],
    },
    {
      heading: 'The AI Content Disclaimer',
      paragraphs: [
        'All course content\u2014lectures, professor profiles, course descriptions\u2014is generated by artificial intelligence systems.',
        'It might be wrong. AI can hallucinate facts, misrepresent concepts, or present outdated information with confidence.',
        'It might be biased. AI models reflect the biases present in their training data.',
        'It\u2019s not peer-reviewed. No subject matter experts have verified this content.',
        'It\u2019s creative fiction. Think of our professors as characters in an elaborate improv show about academia.',
        'If you need actual education, consult real professors, textbooks, and accredited institutions.',
      ],
    },
    {
      heading: 'User-Generated Content',
      paragraphs: [
        'Users can create their own professors, courses, and lectures. Everything said above applies doubly to user-generated content. We don\u2019t review it before publication. We don\u2019t verify its accuracy. We\u2019re not liable for what users create.',
      ],
    },
    {
      heading: 'Our Right to Moderate',
      paragraphs: [
        'We reserve the right to curate this platform as we see fit. Specifically, we can:',
      ],
      items: [
        'Delete any content at any time, for any reason or no reason',
        'Edit content to fix errors, remove problematic material, or improve quality',
        'Make content private (visible only to its creator) without warning',
        'Ban users who violate these terms or applicable law',
      ],
    },
    {
      heading: 'Privacy',
      paragraphs: [
        'We collect minimal personal data. For details on what we collect and how we use it, see our Privacy Policy.',
      ],
    },
    {
      heading: 'Intellectual Property & Licensing',
      paragraphs: [
        'Content is open: All educational content on ArtificialU\u2014lectures, course materials, AI-generated text and audio\u2014is released under Creative Commons Attribution 4.0 International (CC BY 4.0).',
        'This means you can copy, remix, and redistribute any lecture or course content; use it in your own projects; modify it and create derivative works; and use it commercially. All we ask is attribution: mention ArtificialU and link back when practical.',
        'Platform code: The source code for this platform is available on GitHub under the AGPL-3.0 license.',
        'What\u2019s not CC-licensed: The ArtificialU name, logo, and visual design are our trademarks. You can\u2019t rebrand this platform as your own, but you\u2019re welcome to build something inspired by it.',
      ],
    },
    {
      heading: 'Prohibited Uses',
      paragraphs: ['The following are not permitted:'],
      items: [
        'Using our service to generate spam, misinformation campaigns, or harmful content',
        'Impersonating real people or institutions',
        'Hacking, exploiting, or abusing our systems',
        'Violating any applicable laws',
        'Misrepresenting the source or nature of AI-generated content',
      ],
    },
    {
      heading: 'Disclaimers & Limitations',
      paragraphs: [
        'As-is service: We provide ArtificialU without warranties of any kind. It might break. Content might disappear. We\u2019re doing our best, but things happen.',
        'No liability: We\u2019re not liable for any damages arising from your use of this service\u2014not for bad grades from citing our AI-generated lectures, not for existential crises about the nature of education, nothing.',
        'Jurisdiction: These terms are governed by the laws of the State of Minnesota. Disputes will be resolved in the state or federal courts located in Hennepin County, Minnesota.',
      ],
    },
    {
      heading: 'Changes to These Terms',
      paragraphs: [
        'We may update these terms occasionally. We\u2019ll note the revision date at the top. Continued use means you accept the new terms.',
      ],
    },
    {
      heading: 'Contact',
      paragraphs: [
        'Questions? Concerns? Existential dread about AI-generated education? Email us at: ben@aliencyb.org',
      ],
    },
  ],
  closing:
    'This is an experiment\u2014a playful exploration of what AI can do with educational content. Treat it as such. Learn, explore, have fun, but don\u2019t confuse this with actual university coursework. Welcome to ArtificialU.',
}
