"""
Configuration modules for the ArtificialU system.
"""

from artificial_u.config.defaults import (
    DEFAULT_DB_URL,
    DEFAULT_AUDIO_PATH,
    DEFAULT_TEXT_EXPORT_PATH,
    DEFAULT_CONTENT_BACKEND,
    DEFAULT_OLLAMA_MODEL,
    PROFESSOR_TITLES,
    PROFESSOR_LAST_NAMES,
    DEPARTMENTS,
    DEPARTMENT_SPECIALIZATIONS,
    TEACHING_STYLES,
    PERSONALITIES,
    DEFAULT_COURSE_LEVEL,
    DEFAULT_COURSE_WEEKS,
    DEFAULT_LECTURES_PER_WEEK,
    DEFAULT_LECTURE_WORD_COUNT,
    DEFAULT_LOG_LEVEL,
)

__all__ = [
    "DEFAULT_DB_URL",
    "DEFAULT_AUDIO_PATH",
    "DEFAULT_TEXT_EXPORT_PATH",
    "DEFAULT_CONTENT_BACKEND",
    "DEFAULT_OLLAMA_MODEL",
    "PROFESSOR_TITLES",
    "PROFESSOR_LAST_NAMES",
    "DEPARTMENTS",
    "DEPARTMENT_SPECIALIZATIONS",
    "TEACHING_STYLES",
    "PERSONALITIES",
    "DEFAULT_COURSE_LEVEL",
    "DEFAULT_COURSE_WEEKS",
    "DEFAULT_LECTURES_PER_WEEK",
    "DEFAULT_LECTURE_WORD_COUNT",
    "DEFAULT_LOG_LEVEL",
]
