"""Add created_at and updated_at timestamps to all tables

Revision ID: 0dc66709d46a
Revises: 4f1c0e7b2c01
Create Date: 2025-09-20 00:52:56.113740

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0dc66709d46a"
down_revision = "4f1c0e7b2c01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timestamp columns with default values to handle existing data
    op.add_column(
        "courses",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "courses",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "departments",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "departments",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.alter_column(
        "jobs", "kind", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "jobs",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.drop_index(op.f("idx_jobs_status_priority_runafter"), table_name="jobs")
    op.create_index(
        "idx_jobs_status_priority_runafter",
        "jobs",
        ["status", "priority", "run_after"],
        unique=False,
    )
    op.add_column(
        "lectures",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "lectures",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "professors",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "professors",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "topics",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    op.add_column(
        "topics",
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "updated_at")
    op.drop_column("topics", "created_at")
    op.drop_column("professors", "updated_at")
    op.drop_column("professors", "created_at")
    op.drop_column("lectures", "updated_at")
    op.drop_column("lectures", "created_at")
    op.drop_index("idx_jobs_status_priority_runafter", table_name="jobs")
    op.create_index(
        op.f("idx_jobs_status_priority_runafter"),
        "jobs",
        ["status", sa.literal_column("priority DESC"), "run_after"],
        unique=False,
    )
    op.alter_column(
        "jobs",
        "status",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "jobs", "kind", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.drop_column("departments", "updated_at")
    op.drop_column("departments", "created_at")
    op.drop_column("courses", "updated_at")
    op.drop_column("courses", "created_at")
    # ### end Alembic commands ###
