"""add topic:content, lecture:title

Revision ID: 48b47ee46467
Revises: a49c9875c8a8
Create Date: 2025-07-16 16:18:22.190572

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "48b47ee46467"
down_revision = "a49c9875c8a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lectures", sa.Column("title", sa.String(), nullable=True))
    op.add_column(
        "topics", sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.alter_column(
        "voices",
        "verified_languages",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voices",
        "verified_languages",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("topics", "content")
    op.drop_column("lectures", "title")
    # ### end Alembic commands ###
