"""Add attribution fields to professors and topics

Revision ID: 48ef6feae5ea
Revises: e5f088fb3683
Create Date: 2025-10-20 22:03:59.453179

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "48ef6feae5ea"
down_revision = "e5f088fb3683"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("professors", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("professors", sa.Column("created_with", sa.String(), nullable=True))
    op.create_foreign_key(None, "professors", "students", ["created_by"], ["id"])
    op.add_column("topics", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("topics", sa.Column("created_with", sa.String(), nullable=True))
    op.create_foreign_key(None, "topics", "students", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "topics", type_="foreignkey")
    op.drop_column("topics", "created_with")
    op.drop_column("topics", "created_by")
    op.drop_constraint(None, "professors", type_="foreignkey")
    op.drop_column("professors", "created_with")
    op.drop_column("professors", "created_by")
    # ### end Alembic commands ###
