"""add_unique_constraint_topic_course_week_order

Revision ID: 4a88cb5f6566
Revises: 48b47ee46467
Create Date: 2025-07-17 03:30:59.123579

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a88cb5f6566"
down_revision = "48b47ee46467"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lectures", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(
        "uq_topic_course_week_order", "topics", ["course_id", "week", "order"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_topic_course_week_order", "topics", type_="unique")
    op.alter_column("lectures", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
