"""add tts backend and model to lectures

Revision ID: 4cd3c3079cb3
Revises: eaeabaf37c08
Create Date: 2026-10-06 02:19:16.319300

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4cd3c3079cb3"
down_revision = "eaeabaf37c08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lectures", sa.Column("tts_backend", sa.String(length=50), nullable=True))
    op.add_column("lectures", sa.Column("tts_model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lectures", "tts_model")
    op.drop_column("lectures", "tts_backend")
    # ### end Alembic commands ###
