"""rm generated_at

Revision ID: 95816da14c74
Revises: 92444c4efe6c
Create Date: 2025-04-27 22:38:34.341399

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "95816da14c74"
down_revision = "92444c4efe6c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "generated_at")
    op.drop_column("lectures", "generated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lectures",
        sa.Column(
            "generated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "generated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
