"""rm course syllabus

Revision ID: afa3da9e5fee
Revises: 3d060fc71377
Create Date: 2025-05-01 00:31:41.443103

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "afa3da9e5fee"
down_revision = "3d060fc71377"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses",
        "topics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_column("courses", "syllabus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("syllabus", sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column(
        "courses",
        "topics",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
