"""Add created_by and created_with to lectures

Revision ID: e5f088fb3683
Revises: 81afa3f0aebc
Create Date: 2025-10-20 01:01:56.631039

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e5f088fb3683"
down_revision = "81afa3f0aebc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lectures", sa.Column("created_by", sa.Integer(), nullable=True))
    op.add_column("lectures", sa.Column("created_with", sa.String(), nullable=True))
    op.create_foreign_key(None, "lectures", "students", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lectures", type_="foreignkey")
    op.drop_column("lectures", "created_with")
    op.drop_column("lectures", "created_by")
    # ### end Alembic commands ###
