"""add tags and course_tags tables

Revision ID: eaeabaf37c08
Revises: b1c2d3e4f5a6
Create Date: 2026-07-02 01:52:37.482948

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eaeabaf37c08"
down_revision = "b1c2d3e4f5a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "language", name="uq_tags_slug_language"),
    )
    op.create_table(
        "course_tags",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("course_id", "tag_id"),
    )
    op.create_index("idx_course_tags_tag_id", "course_tags", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_course_tags_tag_id", table_name="course_tags")
    op.drop_table("course_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
