import { Hero } from '../components/ui'

const Home = () => {
  return (
    <div>
      {/* Hero Section */}
      <Hero
        title="Artificial University"
        subtitle="Explore knowledge crafted by AI, shaped by your curiosity"
        buttonText="Browse Courses"
        buttonLink="/courses"
      />

      {/* Disclaimer Notice */}
      <section class="py-8 bg-arcanum-900">
        <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="border-2 border-red-500 bg-red-900/20 rounded-lg p-6">
            <div class="flex items-start gap-4">
              <div class="flex-shrink-0 text-red-400 text-2xl font-bold">⚠</div>
              <div class="flex-1">
                <h2 class="text-xl font-display text-red-300 mb-3 font-bold">
                  Experimental Content — Not a Real University
                </h2>
                <div class="space-y-2 font-serif text-parchment-200">
                  <p class="font-semibold">
                    This is an alpha-stage experimental project. All content is AI-generated for
                    entertainment purposes only.
                  </p>
                  <p>
                    Artificial University is NOT an accredited institution. We do not offer real
                    courses, degrees, or academic credits. All professors, departments, and lectures
                    are fictional and generated by artificial intelligence.
                  </p>
                  <p>
                    Content may contain errors and should not be used for formal education. See our{' '}
                    <a href="/about" class="text-red-300 hover:text-red-200 underline">
                      About page
                    </a>{' '}
                    for full details.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Welcome Section */}
      <section class="py-20 bg-arcanum-900 relative overflow-hidden">
        {/* Background effect */}
        <div class="absolute inset-0 opacity-20" aria-hidden="true">
          <div class="absolute top-0 right-0 w-1/2 h-full bg-vaporwave-800/10 rounded-full filter blur-3xl" />
        </div>

        <div class="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="prose prose-lg prose-invert mx-auto font-serif text-parchment-300">
            <p class="text-lg md:text-xl leading-relaxed">
              Welcome to the Artificial University. Here you'll find a growing collection of courses
              generated through a collaboration between artificial intelligence and human expertise.
              Each course is designed to make complex subjects accessible and engaging.
            </p>
            <p class="text-lg md:text-xl leading-relaxed">
              Explore our curriculum, learn from our faculty, and discover new fields of study.
            </p>
          </div>

          <div class="mt-12 text-center">
            <a
              href="/courses"
              class="inline-block px-6 py-3 border border-parchment-400 text-parchment-200 bg-arcanum-800/50 hover:bg-arcanum-700/50 transition-colors duration-300 rounded font-serif tracking-wider"
            >
              View All Courses
            </a>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Home
