/**
 * English translations
 */
export const en = {
  // Site branding
  site: {
    name: 'ARTIFICIAL UNIVERSITY',
    shortName: 'A|U',
  },

  // Navigation
  nav: {
    about: 'About',
    academics: 'Academics',
    professors: 'Professors',
    courses: 'Courses',
    profile: 'Profile',
    jobs: 'Jobs',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    openMenu: 'Open main menu',
  },

  // Home page
  home: {
    hero: {
      title: 'Artificial University',
      subtitle: 'Explore knowledge crafted by AI, shaped by your curiosity',
      buttonText: 'Learn More',
    },
    disclaimer: {
      title: 'Experimental Content — Not a Real University',
      alphaNotice:
        'This is an alpha-stage experimental project. All content is AI-generated for entertainment purposes only.',
      notAccredited:
        'Artificial University is NOT an accredited institution. We do not offer real courses, degrees, or academic credits. All professors, departments, and lectures are fictional and generated by artificial intelligence.',
      noFormalEducation:
        'Content may contain errors and should not be used for formal education. See our',
      aboutLink: 'About page',
      forFullDetails: 'for full details.',
    },
    welcome: {
      intro:
        'Welcome to the Artificial University. Discover AI-generated audio courses that make complex subjects easy to absorb.',
      explore:
        'Explore the curriculum, listen to dynamic lectures, and uncover new fields of study. Log in to create your own courses.',
      viewAllCourses: 'View All Courses',
    },
  },

  // About page
  about: {
    title: 'About Artificial University',
    subtitle: 'An experimental AI content platform',
    importantNotice: {
      title: 'Important Notice',
      notAccredited: 'Artificial University is NOT an accredited educational institution.',
      experimental:
        'This platform is an experimental project that uses artificial intelligence to generate educational content. All courses, professors, departments, and lectures on this site are AI-generated and created for entertainment and experimental purposes only.',
      alphaStage:
        'This is an alpha-stage project in active development. Content may be inaccurate, incomplete, or subject to change without notice. Do not rely on this content for formal education, professional certification, or any official academic purpose.',
    },
    whatThisIs: {
      title: 'What This Is',
      content:
        'Artificial University is an experimental platform that explores what happens when we use large language models to generate complete educational content. The entire curriculum—from department structures to course syllabi, professor personalities, and lecture content—is created by AI systems.',
    },
    howItWorks: {
      title: 'How It Works',
      intro:
        'Using various AI models (including Claude, GPT, and others), the platform generates: courses across diverse academic fields, fictional professor profiles with distinct teaching styles and personalities, structured lecture content organized by topics and weeks, and text-to-speech audio versions of lectures using voice synthesis.',
      outro:
        'Users can create new courses, customize parameters, and explore AI-generated academic content. This is primarily a creative and technical experiment in automated content generation.',
    },
    whatThisIsNot: {
      title: 'What This Is NOT',
      content:
        'This platform does not offer real courses, accredited programs, academic credits, degrees or certificates, qualified instruction from human experts, or verified educational content. No one affiliated with this project is your teacher, mentor, or academic advisor.',
    },
    alphaStatus: {
      title: 'Alpha Status',
      content:
        'This project is in early alpha development. Expect bugs, incomplete features, and significant changes. The AI-generated content has not been reviewed for accuracy and may contain errors, biases, or outdated information. Use this platform at your own discretion and for entertainment purposes only.',
    },
    openSource: {
      title: 'Open Source',
      content:
        'Artificial University is an open-source project. You can view the source code, report issues, or contribute to development on GitHub.',
      viewOnGitHub: 'View on GitHub',
    },
    creator: {
      title: 'About the Creator',
      bio: 'Artificial-U is created and maintained by me, Bennie Rosas. I write music and software in Minneapolis. I graduated from The Evergreen State College. Contact me at',
      outro:
        'I built this as a fun experiment, designed to spark joy and curiosity. I hope you enjoy it too. Reach out to share your thoughts.',
    },
    exploreCourses: 'Explore Courses',
  },

  // Common UI elements
  common: {
    loading: 'Loading...',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    close: 'Close',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    viewAll: 'View All',
  },
}

export type Locale = typeof en
