/**
 * English translations
 */
export const en = {
  // Site branding
  site: {
    name: 'ARTIFICIAL UNIVERSITY',
    shortName: 'A|U',
  },

  // Navigation
  nav: {
    about: 'About',
    academics: 'Academics',
    professors: 'Professors',
    search: 'Search',
    courses: 'Courses',
    profile: 'Profile',
    jobs: 'Jobs',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    openMenu: 'Open main menu',
  },

  // Home page
  home: {
    hero: {
      titleStart: 'Lectures delivered by ',
      titleEmphasis: 'AI professors',
      titleEnd: ", on any subject you're curious about",
      subtitle:
        'Each course is taught by a unique AI professor with their own voice, personality, and teaching style. Browse the catalog, press play, and learn something new.',
      browseCta: 'Browse & Listen',
      createCta: 'Create Your Own Course',
    },
    featuredLectures: {
      label: 'Featured Lectures',
      nowPlaying: 'Featured Lectures',
    },
    stats: {
      courses: 'Courses',
      lectures: 'Lectures',
      audioHours: 'Hours of Audio',
    },
    disclaimer: {
      title: 'Experimental Content — Not a Real University',
      alphaNotice:
        'This is an alpha-stage experimental project. All content is AI-generated for entertainment purposes only.',
      notAccredited:
        'Artificial University is NOT an accredited institution. We do not offer real courses, degrees, or academic credits. All professors, departments, and lectures are fictional and generated by artificial intelligence.',
      noFormalEducation:
        'Content may contain errors and should not be used for formal education. See our',
      aboutLink: 'About page',
      forFullDetails: 'for full details.',
    },
    ctaBanner: {
      title: 'Create your own courses',
      description:
        'Design a course on any subject. Choose a professor persona — or let us generate one — and we\u2019ll produce full audio lectures in their voice and style. From quantum mechanics to queer theory, from Baroque counterpoint to blockchain.',
      feature1: 'AI-generated lectures',
      feature2: 'Professional text-to-speech',
      feature3: 'Unique professor voices',
      cta: 'Get Started Free',
      priceHint: '50 free coins on signup \u00B7 then from $5',
    },
    howItWorks: {
      sectionLabel: 'For creators',
      title: 'How It Works',
      step1Title: 'Pick a Subject',
      step1Desc:
        'Choose a department and topic, or describe what you want to learn. The system generates a structured course with weekly topics and learning objectives.',
      step2Title: 'Meet Your Professor',
      step2Desc:
        'Each course gets a professor with a unique personality, teaching style, accent, and voice. You can customize them or let the system surprise you.',
      step3Title: 'Listen & Share',
      step3Desc:
        'AI generates full lecture content in the professor\u2019s voice and converts it to audio. Listen in the browser, download, or share with the community.',
    },
    trust: {
      sectionLabel: 'Transparency & trust',
      title: 'Built Responsibly',
      aiTitle: 'AI Transparency',
      aiDesc:
        "All content is AI-generated using large language models (Claude, GPT, Gemini) and professional text-to-speech. We're upfront about what's synthetic and what isn't.",
      aiLink: 'Read our AI usage policy \u2192',
      privacyTitle: 'Privacy First',
      privacyDesc:
        'Minimal data collection. Authentication via Auth0. No tracking cookies, no ad networks, no data brokering. Your learning is your business.',
      privacyLink: 'Privacy policy \u2192',
      notReplacementTitle: 'Not a Replacement',
      notReplacementDesc:
        'This is a learning supplement and creative tool, not accredited education. AI professors are fictional characters. Content may contain errors \u2014 think of it as a starting point, not a textbook.',
      notReplacementLink: 'Terms of service \u2192',
    },
    welcome: {
      intro:
        'Welcome to the Artificial University. Discover AI-generated audio courses that make complex subjects easy to absorb.',
      explore:
        'Explore the curriculum, listen to dynamic lectures, and uncover new fields of study. Log in to create your own courses.',
      viewAllCourses: 'View All Courses',
    },
  },

  // About page
  about: {
    title: 'About Artificial University',
    subtitle: 'An experimental AI content platform',
    importantNotice: {
      title: 'Important Notice',
      notAccredited: 'Artificial University is NOT an accredited educational institution.',
      experimental:
        'This platform is an experimental project that uses artificial intelligence to generate educational content. All courses, professors, departments, and lectures on this site are AI-generated and created for entertainment and experimental purposes only.',
      alphaStage:
        'This is an alpha-stage project in active development. Content may be inaccurate, incomplete, or subject to change without notice. Do not rely on this content for formal education, professional certification, or any official academic purpose.',
    },
    whatThisIs: {
      title: 'What This Is',
      content:
        'Artificial University is an experimental platform that explores what happens when we use large language models to generate complete educational content. The entire curriculum—from department structures to course syllabi, professor personalities, and lecture content—is created by AI systems.',
    },
    howItWorks: {
      title: 'How It Works',
      intro:
        'Using various AI models (including Claude, GPT, and others), the platform generates: courses across diverse academic fields, fictional professor profiles with distinct teaching styles and personalities, structured lecture content organized by topics and weeks, and text-to-speech audio versions of lectures using voice synthesis.',
      outro:
        'Users can create new courses, customize parameters, and explore AI-generated academic content. This is primarily a creative and technical experiment in automated content generation.',
    },
    whatThisIsNot: {
      title: 'What This Is NOT',
      content:
        'This platform does not offer real courses, accredited programs, academic credits, degrees or certificates, qualified instruction from human experts, or verified educational content. No one affiliated with this project is your teacher, mentor, or academic advisor.',
    },
    alphaStatus: {
      title: 'Alpha Status',
      content:
        'This project is in early alpha development. Expect bugs, incomplete features, and significant changes. The AI-generated content has not been reviewed for accuracy and may contain errors, biases, or outdated information. Use this platform at your own discretion and for entertainment purposes only.',
    },
    openSource: {
      title: 'Open Source',
      content:
        'Artificial University is an open-source project. You can view the source code, report issues, or contribute to development on GitHub.',
      viewOnGitHub: 'View on GitHub',
    },
    creator: {
      title: 'About the Creator',
      bio: 'Artificial-U is created and maintained by me, Bennie Rosas. I write music and software in Minneapolis. I graduated from The Evergreen State College. Contact me at',
      outro:
        'I built this as a fun experiment, designed to spark joy and curiosity. I hope you enjoy it too. Reach out to share your thoughts.',
    },
    exploreCourses: 'Explore Courses',
  },

  // Search
  search: {
    placeholder: 'Search lectures, courses, professors, topics\u2026',
    title: 'Search Results',
    resultsFor: 'Results for',
    noResults: 'No results found. Try a different search term.',
    lectures: 'Lectures',
    courses: 'Courses',
    professors: 'Professors',
    departments: 'Departments',
    topics: 'Topics',
    viewAll: 'View all',
  },

  // Footer
  footer: {
    tagline:
      'AI-powered educational audio content. Explore knowledge crafted by AI, shaped by your curiosity.',
    explore: 'Explore',
    allCourses: 'All Courses',
    departments: 'Departments',
    professors: 'Professors',
    search: 'Search',
    create: 'Create',
    getStarted: 'Get Started',
    pricing: 'Pricing',
    howItWorks: 'How It Works',
    faq: 'FAQ',
    about: 'About',
    aboutProject: 'About the Project',
    aiEthics: 'AI Usage & Ethics',
    contact: 'Contact',
    github: 'GitHub',
    copyright: '\u00A9 2026 Artificial University. An indie project by Bennie Rosas.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    aiTransparency: 'AI Transparency',
  },

  // Common UI elements
  common: {
    loading: 'Loading...',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    close: 'Close',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    viewAll: 'View All',
    previous: 'Previous',
    retry: 'Retry',
    refresh: 'Refresh',
    saving: 'Saving...',
    deleting: 'Deleting...',
    generating: 'Generating...',
    uploading: 'Uploading...',
    exporting: 'Exporting...',
    cancelling: 'Cancelling...',
    adding: 'Adding...',
    unknownError: 'Unknown error',
    notProvided: 'Not provided',
    noDescription: 'No description available.',
    nA: 'N/A',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    page: 'Page',
    of: 'of',
    ascending: 'Ascending',
    descending: 'Descending',
    update: 'Update',
    clear: 'Clear',
    generate: 'Generate',
    generateImage: 'Generate Image',
    regenerateImage: 'Regenerate Image',
    failedToGenerateImage: 'Failed to generate image',
    creating: 'Creating...',
  },

  // Academics page
  academics: {
    title: 'Academics',
    faculties: 'Faculties',
    departments: 'Departments',
    seeAllDepartments: 'see all departments',
    loadingFaculties: 'Loading faculties...',
    loadingDepartments: 'Loading departments...',
    errorLoadingFaculties: 'Error loading faculties',
    errorLoadingDepartments: 'Error loading departments',
    noFacultiesFound: 'No faculties found',
    noDepartmentsFound: 'No departments found for this faculty.',
  },

  // Courses page
  courses: {
    title: 'Academic Courses',
    addCourse: 'Add Course',
    createNewCourse: 'Create New Course',
    filterByDepartment: 'Filter by Department',
    allDepartments: 'All Departments',
    clearFilter: 'Clear filter',
    myCourses: 'My Courses',
    myCoursesOnly: 'My Courses Only',
    hiddenCourses: 'Hidden Courses',
    sortField: 'Sort field',
    sortBy: 'Sort by',
    order: 'Order',
    code: 'Code',
    courseTitle: 'Title',
    level: 'Level',
    status: 'Status',
    courseImage: 'Course image',
    lastUpdate: 'Last Update',
    created: 'Created',
    teacher: 'Teacher',
    department: 'Department',
    creator: 'Creator',
    audioFiles: 'Audio Files',
    audioCoverage: 'Audio Coverage',
    updated: 'Updated',
    viewCourse: 'View course →',
    loading: 'Loading courses...',
    errorLoading: 'Error loading courses',
    noCoursesFound: 'No courses found',
    courseCreationFailed: 'Course creation failed',
    failedToEnqueue: 'Failed to enqueue course creation',
    form: {
      connectedCourses: 'Connected Courses',
      connectedCoursesHelper: 'Only courses from the selected department are shown.',
      noCoursesInDepartment: 'No courses found in this department.',
      codeLabel: 'Course Code',
      titleLabel: 'Course Title',
      departmentLabel: 'Department',
      professorLabel: 'Professor',
      levelLabel: 'Course Level',
      lecturesPerWeekLabel: 'Lectures per Week (Optional)',
      totalWeeksLabel: 'Total Weeks (Optional)',
      descriptionLabel: 'Description',
      aiPromptLabel: 'AI Generation Prompt (Optional)',
      departmentPlaceholder: '-- Select Department (Optional) --',
      professorPlaceholder: '-- Select Professor (Optional) --',
      levelPlaceholder: '-- Select Level (Optional) --',
      levelUndergraduate: 'Undergraduate',
      levelGraduate: 'Graduate',
      aiDeterminesDepartment: 'AI will determine a department',
      aiDeterminesProfessor: 'AI will determine a professor',
      aiDeterminesLevel: 'AI will determine the level',
      lecturesPerWeekHelper: 'Number of lectures per week (1–5)',
      totalWeeksHelper: 'Total number of weeks (1–50)',
      aiPromptHelper:
        'Provide a freeform prompt to guide AI generation for topics, detailed description, etc.',
      codeRequired: 'Course code is required.',
      titleRequired: 'Course title is required.',
      descriptionRequired: 'Description is required.',
      lecturesPerWeekRange: 'Lectures per week must be between 1 and 5 if specified.',
      totalWeeksRange: 'Total weeks must be between 1 and 50 if specified.',
      failedToLoadDepartments: 'Failed to load departments',
      failedToLoadProfessors: 'Failed to load professors',
      failedToGenerate: 'Failed to generate course details',
      generateDetails: 'Generate Details',
      updateCourse: 'Update Course',
      saveCourse: 'Save Course',
    },
  },

  // Professors page
  professors: {
    title: 'Professors',
    addProfessor: 'Add Professor',
    createNewProfessor: 'Create New Professor',
    searchPlaceholder: 'Search professors...',
    allFaculties: 'All Faculties',
    allDepartments: 'All Departments',
    loadingFaculties: 'Loading faculties...',
    loadingDepartments: 'Loading departments...',
    loading: 'Loading professors...',
    errorLoading: 'Error loading professors',
    noProfessorsFound: 'No professors found',
    failedToCreate: 'Failed to create professor',
    form: {
      nameLabel: 'Professor Name',
      titleLabel: 'Title',
      departmentLabel: 'Department',
      specializationLabel: 'Specialization',
      descriptionLabel: 'Description',
      backgroundLabel: 'Background',
      personalityLabel: 'Personality',
      teachingStyleLabel: 'Teaching Style',
      genderLabel: 'Gender',
      accentLabel: 'Accent',
      ageLabel: 'Age',
      aiPromptLabel: 'AI Generation Prompt (Optional)',
      departmentPlaceholder: '-- Select Department --',
      departmentHelper: 'Department affiliation.',
      specializationHelper: 'Primary field of expertise.',
      aiPromptHelper:
        'Provide a freeform prompt to guide AI generation for personality, background, teaching style, etc.',
      nameRequired: 'Professor name is required',
      titleRequired: 'Title is required',
      agePositive: 'Age must be a positive number.',
      failedToGenerate: 'Failed to generate professor profile',
    },
  },

  // Departments page
  departments: {
    title: 'Departments',
    addDepartment: 'Add Department',
    createNewDepartment: 'Create New Department',
    searchPlaceholder: 'Search departments...',
    allFaculties: 'All Faculties',
    loadingFaculties: 'Loading faculties...',
    loading: 'Loading departments...',
    errorLoading: 'Error loading departments',
    noDepartmentsFound: 'No departments found',
    failedToCreate: 'Failed to create department',
    form: {
      nameLabel: 'Department Name',
      codeLabel: 'Department Code',
      facultyLabel: 'Faculty',
      descriptionLabel: 'Description',
      codeHelperText: 'Must be between 2 and 10 characters.',
      facultyPlaceholder: 'Select a faculty',
      facultyLoading: 'Loading faculties...',
      nameRequired: 'Department name is required',
      codeRequired: 'Department code is required',
      codeLengthError: 'Code must be between 2 and 10 characters',
      facultyRequired: 'Faculty is required',
      descriptionRequired: 'Description is required',
      failedToGenerate: 'Failed to generate department',
    },
  },

  // Profile page
  profile: {
    title: 'My Profile',
    loading: 'Loading profile...',
    name: 'Name',
    email: 'Email',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully!',
    failedToLoad: 'Failed to load profile',
    failedToUpdate: 'Failed to update profile',
    enrollmentStatus: 'Enrollment Status',
    status: 'Status',
    coinBalance: 'Coin Balance',
    coins: 'coins',
    accountInformation: 'Account Information',
    accountId: 'Account ID',
    authId: 'Auth ID',
    accountActive: 'Account Active',
    roles: {
      viewer: 'Audit Only',
      creator: 'Enrolled',
      admin: 'Admin',
    },
    contentLanguage: 'Content Language',
    contentLanguageDesc:
      'Choose which language\'s content to browse. "Auto" follows your UI language when supported.',
    contentLanguageAuto: 'Auto (follow UI)',
    contentLanguageEn: 'English',
    contentLanguageFr: 'Français',
  },

  // Admin Dashboard
  admin: {
    title: 'Admin Dashboard',
    filterByRole: 'Filter by Role',
    allRoles: 'All Roles',
    role: 'Role',
    viewer: 'Viewer',
    creator: 'Creator',
    admin: 'Admin',
    active: 'Active',
    inactive: 'Inactive',
    amount: 'Amount',
    addCoins: 'Add Coins',
    roleUpdated: 'Role updated successfully for student',
    failedToUpdateRole: 'Failed to update role',
    pleaseEnterValidCoins: 'Please enter a valid positive number of coins',
    addedCoins: 'Added',
    coinsToStudent: 'coins to student',
    failedToAddCoins: 'Failed to add coins',
    errorLoading: 'Error loading students',
    unknownError: 'Unknown error',
  },

  // Jobs page
  jobs: {
    title: 'Background Jobs',
    all: 'All',
    queued: 'Queued',
    running: 'Running',
    done: 'Done',
    failed: 'Failed',
    cancelled: 'Cancelled',
    cancel: 'Cancel',
    cancelJob: 'Cancel Job',
    confirmCancel: 'Are you sure you want to cancel this job?',
    failedToCancel: 'Failed to cancel job. Please try again.',
    noErrorAvailable: 'No error message available',
    errorLoading: 'Error loading jobs',
  },

  // Course Detail page
  courseDetail: {
    department: 'Department',
    professor: 'Professor',
    loadingDepartment: 'Loading department...',
    loadingProfessor: 'Loading professor...',
    departmentNotAvailable: 'Department info not available.',
    professorNotAvailable: 'Professor info not available.',
    faculty: 'Faculty',
    topics: 'Topics',
    lectures: 'Lectures',
    noTopicsFound: 'No topics found in this course.',
    noLecturesFound: 'No lectures found in this topic.',
    loadingTopics: 'Loading topics...',
    loadingLectures: 'Loading lectures...',
    errorLoadingTopics: 'Error loading topics',
    errorLoadingLectures: 'Error loading lectures',
    playAudio: 'Play lecture audio',
    listenAudio: 'Listen to lecture audio',
    downloadAudio: 'Download lecture audio',
    openDetail: 'Open lecture detail',
    editCourse: 'Edit Course',
    deleteCourse: 'Delete Course',
    export: 'Export',
    exporting: 'Exporting...',
    deleting: 'Deleting...',
    failedToUpdate: 'Failed to update course',
    failedToDelete: 'Failed to delete course',
    failedToExport: 'Failed to export course',
    level: 'Level',
    noTopicsDefined: 'No topics defined for this course.',
    generatingTopics: 'Generating course topics...',
    week: 'Week',
    topic: 'Topic',
    lecture: 'Lecture',
    invalidCourseId: 'Invalid Course ID.',
    loadingCourse: 'Loading course details...',
    courseNotFound: 'Course not found.',
    backToCourses: 'Back to Courses',
    backToCourse: 'Back to Course',
    publishing: 'Publishing...',
    publishCourse: 'Publish Course',
    failedToPublish: 'Failed to publish course',
    exportJobEnqueued: 'Export job enqueued. Check the Jobs page for status.',
    viewJobStatus: 'View job status',
    confirmDeletion: 'Confirm Deletion',
    confirmDeleteMessage:
      'Are you sure you want to delete this course? This action cannot be undone.',
    published: 'Published',
    hidden: 'Hidden',
    courseDetails: 'Course Details',
    courseTopics: 'Course Topics',
    lecturesPerWeek: 'Lectures per week',
    totalWeeks: 'Total weeks',
    editTopics: 'Edit Topics',
    topicsForCourse: 'Topics for {code}: {title}',
    manageTopicsDescription: 'Manage the topics and content structure for this course.',
    topicGenerationInProgress:
      'Topic generation in progress. The page will update automatically when complete.',
  },

  // Department Detail page
  departmentDetail: {
    courses: 'Courses',
    professors: 'Professors',
    loadingCourses: 'Loading courses...',
    loadingProfessors: 'Loading professors...',
    errorLoadingCourses: 'Error loading courses',
    errorLoadingProfessors: 'Error loading professors',
    noCoursesFound: 'No courses found in this department.',
    noProfessorsFound: 'No professors found in this department.',
    editDepartment: 'Edit Department',
    deleteDepartment: 'Delete Department',
    failedToLoad: 'Failed to load department',
    failedToUpdate: 'Failed to update department',
    failedToDelete: 'Failed to delete department',
    invalidDepartmentId: 'Invalid department ID',
    level: 'Level',
  },

  // Lecture Detail page
  lectureDetail: {
    generatingAudio: 'Generating Audio...',
    regenerateAudio: 'Regenerate Audio',
    generateAudio: 'Generate Audio',
    uploadAudio: 'Upload Audio',
    uploading: 'Uploading...',
    delete: 'Delete',
    deleting: 'Deleting...',
    deleteLecture: 'Delete Lecture',
    confirmDelete: 'Delete',
    failedToUpdate: 'Failed to update lecture',
    failedToDelete: 'Failed to delete lecture',
    failedToGenerateAudio: 'Failed to generate audio',
    pleaseSelectAudioFile: 'Please select an audio file (MP3 recommended)',
    fileSizeLimit: 'File size must be less than 50MB',
    failedToUploadAudio: 'Failed to upload audio',
    errorLoading: 'Failed to load lecture',
    invalidLectureId: 'Invalid Lecture ID.',
    loadingLecture: 'Loading lecture...',
    viewTranscript: 'View Transcript',
    transcript: 'Transcript',
    listen: 'Listen',
    play: 'Play',
    download: 'Download',
    noContent: 'No content defined for this lecture.',
    revision: 'Revision',
    backToTopic: 'Back to Topic',
    topicContext: 'Topic: Week {week} · Lecture {order} — {title}',
    confirmDeleteMessage: 'Are you sure you want to delete the lecture "{title}"?',
    confirmDeleteUndo: 'This action cannot be undone.',
    view: 'View',
    generatingTimeline: 'Generating Timeline...',
    regenerateTimeline: 'Regenerate Timeline',
    generateTimeline: 'Generate Timeline',
    generatingImages: 'Generating Images...',
    regenerateImages: 'Regenerate Lecture Images',
    generateImages: 'Generate Lecture Images',
    resumeImages: 'Resume Image Generation',
    uploadDisabledTooltip:
      'Upload is disabled when lecture audio already exists. Use Regenerate Audio to replace it.',
    confirmRegenerateAudio:
      'Regenerate audio? This replaces the lecture audio and will regenerate the word timeline, then remap the existing lecture image timeline.',
    confirmRegenerateTimeline:
      'Regenerate timeline? This replaces the word timeline and will remap the existing lecture image timeline without regenerating images.',
    confirmRegenerateImages:
      'Regenerate lecture images? This will delete existing slide images where possible and create a new image timeline with newly generated images.',
    generatingSummary: 'Generating Summary...',
    regeneratingSummary: 'Regenerating Summary...',
    regenerateSummary: 'Regenerate Summary',
    generateSummary: 'Generate Summary',
    clearSummary: 'Clear Summary',
    clearSummaryConfirm: 'Are you sure you want to clear the summary for "{title}"?',
    clearSummaryUndo: 'The summary will be removed, but you can regenerate it later.',
    editSummaryHeading: 'Edit Lecture Summary',
    editSummaryDescription: 'Edit the summary for this lecture. Changes will be saved immediately.',
    editSummaryPlaceholder: 'Enter lecture summary...',
    words: 'words',
    upload: 'Upload',
    noLectureCreated: 'No lecture has been created for this topic yet.',
    generationTimeout:
      'The generation request took longer than expected and timed out. This can happen with complex content generation. Please try again.',
    form: {
      editHeading: 'Edit Lecture',
      createHeading: 'Create New Lecture',
      titleLabel: 'Title',
      contentLabel: 'Content',
      titlePlaceholder: 'Enter lecture title',
      contentPlaceholder: 'Enter lecture content...',
      contentHelper: 'Enter the lecture content. This will be the main text of the lecture.',
      saveChanges: 'Save Changes',
      createLecture: 'Create Lecture',
      saving: 'Saving...',
      creating: 'Creating...',
    },
    audioGenerationTimeout:
      'The audio generation request timed out. It may still complete in the background. Try refreshing in a bit.',
    audioUploadSuccess: 'Audio file uploaded successfully!',
  },

  // Topic Detail page
  topicDetail: {
    generateLectureText: 'Generate Lecture Text',
    generateLectureWithAudio: 'Generate Lecture with Audio',
    generating: 'Generating...',
    invalidTopicId: 'Invalid Topic ID.',
    loadingTopic: 'Loading topic...',
    previousTopic: 'Previous Topic',
    nextTopic: 'Next Topic',
    noContent: 'No content defined for this topic.',
    backToCourse: 'Back to Course',
    editTopic: 'Edit',
    week: 'Week',
    topic: 'Topic',
    topicContext: 'Topic: Week {week} · Lecture {order} — {title}',
    form: {
      editHeading: 'Edit Topic',
      createHeading: 'Create New Topic',
      titleLabel: 'Title',
      weekLabel: 'Week Number',
      orderLabel: 'Order in Week',
      contentLabel: 'Content (JSON)',
      aiPromptLabel: 'AI Generation Prompt (Optional)',
      titlePlaceholder: 'Enter topic title',
      weekPlaceholder: 'Enter week number',
      orderPlaceholder: 'Enter order within the week',
      contentHelper:
        'Enter JSON content for the topic. Example: lecture text, readings array, objectives array, etc.',
      aiPromptHelper: 'Provide a freeform prompt to guide AI generation for this topic.',
      invalidJsonError: 'Invalid JSON format',
      weekOrderRequired: 'Week and order must be valid numbers before generating.',
      failedToGenerate: 'Failed to generate topic',
      updateLabel: 'Update',
      createLabel: 'Create Topic',
    },
  },

  // Theme Switcher
  theme: {
    selectTheme: 'Select Theme',
    description: 'Choose an aesthetic that matches your scholarly pursuits.',
    darkAcademia: 'Dark Academia',
    darkAcademiaDesc: 'Classical elegance with a scholarly aesthetic',
    vaporwave: 'Vaporwave',
    vaporwaveDesc: 'Retro-futuristic digital aesthetics',
    wabiSabi: 'Wabi Sabi',
    wabiSabiDesc: 'Embracing imperfection and natural simplicity',
    biophilia: 'Biophilia',
    biophiliaDesc: 'Lush greens, floral pops, and natural textures',
    changeTheme: 'Change theme',
    currentTheme: 'Current theme',
  },

  // Login page
  login: {
    redirecting: 'Redirecting to login…',
    clickIfNotRedirected: 'Click here if not redirected',
  },

  // PWA (Progressive Web App)
  pwa: {
    updateAvailable: 'Update Available',
    updateMessage: 'A new version of Artificial University is available. Reload to update.',
    updateNow: 'Update Now',
    later: 'Later',
    installApp: 'Install App',
    installMessage: 'Install Artificial University for quick access and offline use.',
    install: 'Install',
    notNow: 'Not Now',
  },

  // Pricing page
  pricing: {
    title: 'Pricing',
    tagline: 'We\u2019re working on a simple, fair pricing model.',
    taglineDetail:
      'The goal is to cover the cost of running the platform \u2014 AI generation and text-to-speech aren\u2019t free. We\u2019re figuring out what makes sense.',
    currentStatus: 'Current Status',
    currentStatusDetail:
      'ArtificialU is free to use right now, with per-account limits on how many lectures and audio files you can generate. You receive 50 coins when you sign up.',
    coinsExplained:
      'Coins are the internal currency for generation. Each AI lecture costs a small number of coins; audio conversion costs a few more. When you run out, generation is paused \u2014 but browsing and listening to existing content is always free.',
    wantMore: 'Want More Coins?',
    wantMoreDetail:
      'Just email me. I\u2019m happy to top up your account while pricing is still being figured out.',
    contactCta: 'ben@aliencyb.org',
    stayTuned: 'Stay tuned \u2014 a proper pricing page is coming.',
  },

  // Quickstart Wizard
  quickstart: {
    // Access control
    creatorAccessRequired: 'Creator Access Required',
    creatorPrivilegesNeeded: 'The Quickstart feature requires creator privileges.',

    // Step labels
    steps: {
      intent: 'Intent',
      professor: 'Professor',
      complete: 'Complete',
    },

    // Error messages
    errors: {
      failedToCreateCourse: 'Failed to create course. Please try again.',
      failedToFinalize: 'Failed to finalize course. Please try again.',
      failedToSearch: 'Failed to search for courses. Please try again.',
      failedToGenerateVoice: 'Failed to generate voice preview',
      failedToRegenerateImage: 'Failed to regenerate image',
      failedToReassignVoice: 'Failed to reassign voice',
      failedToRegenerateProfessor: 'Failed to regenerate professor',
    },

    // Common actions
    startOver: 'Start Over',

    // Complete step
    courseCreated: 'Course Created!',
    courseBeingPrepared: "Your course is being prepared. You'll be redirected shortly...",

    // Intent step
    intent: {
      title: 'What would you like to learn?',
      subtitle: "Describe your learning goal and we'll create a personalized course for you.",
      placeholder:
        'e.g., I want to understand machine learning fundamentals, including supervised and unsupervised learning algorithms...',
      hint: 'Be as specific as you like - the more detail, the better we can tailor your course.',
      searching: 'Searching...',
      creatingCourse: 'Creating Course...',
      startLearning: 'Start Learning',
      coursesFound: 'We found some courses for you!',
      listenNow: 'Listen Now',
      wantSomethingDifferent: 'Want something different?',
      buildSomethingNew: 'Build Something New',
      creating: 'Creating...',
    },

    // Professor step
    professor: {
      title: 'Meet Your Instructor',
      guideThroughCourse: 'This professor will guide you through',
      teachingStyle: 'Teaching style:',
      hearTheirVoice: 'Hear Their Voice',
      generating: 'Generating...',
      or: 'or',
      sampleVoice: 'Sample Voice',
      useThisTeacher: 'Use This Teacher',
      creatingCourse: 'Creating Course...',
      regenerate: 'Regenerate',
      changeSomething: 'Change Something',
      image: 'Image',
      voice: 'Voice',
      details: 'Details',

      // Image regeneration
      generateNewPortrait: 'Generate a new portrait for',
      regenerateImage: 'Regenerate Image',
      regenerating: 'Regenerating...',

      // Voice reassignment
      assignDifferentVoice: 'Assign a different voice to',
      reassignVoice: 'Reassign Voice',
      assigning: 'Assigning...',

      // Professor regeneration
      describeProfessorPreference: "Describe what kind of professor you'd prefer:",
      professorPromptPlaceholder:
        'e.g., A professor with industry experience, more focus on practical applications, younger and more energetic...',
      generateNewProfessor: 'Generate New Professor',
    },
  },
}

export type Locale = typeof en
