/**
 * English translations
 */
export const en = {
  // Site branding
  site: {
    name: 'ARTIFICIAL UNIVERSITY',
    shortName: 'A|U',
  },

  // Navigation
  nav: {
    about: 'About',
    academics: 'Academics',
    professors: 'Professors',
    courses: 'Courses',
    profile: 'Profile',
    jobs: 'Jobs',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    openMenu: 'Open main menu',
  },

  // Home page
  home: {
    hero: {
      title: 'Artificial University',
      subtitle: 'Explore knowledge crafted by AI, shaped by your curiosity',
      buttonText: 'Learn More',
    },
    disclaimer: {
      title: 'Experimental Content — Not a Real University',
      alphaNotice:
        'This is an alpha-stage experimental project. All content is AI-generated for entertainment purposes only.',
      notAccredited:
        'Artificial University is NOT an accredited institution. We do not offer real courses, degrees, or academic credits. All professors, departments, and lectures are fictional and generated by artificial intelligence.',
      noFormalEducation:
        'Content may contain errors and should not be used for formal education. See our',
      aboutLink: 'About page',
      forFullDetails: 'for full details.',
    },
    welcome: {
      intro:
        'Welcome to the Artificial University. Discover AI-generated audio courses that make complex subjects easy to absorb.',
      explore:
        'Explore the curriculum, listen to dynamic lectures, and uncover new fields of study. Log in to create your own courses.',
      viewAllCourses: 'View All Courses',
    },
  },

  // About page
  about: {
    title: 'About Artificial University',
    subtitle: 'An experimental AI content platform',
    importantNotice: {
      title: 'Important Notice',
      notAccredited: 'Artificial University is NOT an accredited educational institution.',
      experimental:
        'This platform is an experimental project that uses artificial intelligence to generate educational content. All courses, professors, departments, and lectures on this site are AI-generated and created for entertainment and experimental purposes only.',
      alphaStage:
        'This is an alpha-stage project in active development. Content may be inaccurate, incomplete, or subject to change without notice. Do not rely on this content for formal education, professional certification, or any official academic purpose.',
    },
    whatThisIs: {
      title: 'What This Is',
      content:
        'Artificial University is an experimental platform that explores what happens when we use large language models to generate complete educational content. The entire curriculum—from department structures to course syllabi, professor personalities, and lecture content—is created by AI systems.',
    },
    howItWorks: {
      title: 'How It Works',
      intro:
        'Using various AI models (including Claude, GPT, and others), the platform generates: courses across diverse academic fields, fictional professor profiles with distinct teaching styles and personalities, structured lecture content organized by topics and weeks, and text-to-speech audio versions of lectures using voice synthesis.',
      outro:
        'Users can create new courses, customize parameters, and explore AI-generated academic content. This is primarily a creative and technical experiment in automated content generation.',
    },
    whatThisIsNot: {
      title: 'What This Is NOT',
      content:
        'This platform does not offer real courses, accredited programs, academic credits, degrees or certificates, qualified instruction from human experts, or verified educational content. No one affiliated with this project is your teacher, mentor, or academic advisor.',
    },
    alphaStatus: {
      title: 'Alpha Status',
      content:
        'This project is in early alpha development. Expect bugs, incomplete features, and significant changes. The AI-generated content has not been reviewed for accuracy and may contain errors, biases, or outdated information. Use this platform at your own discretion and for entertainment purposes only.',
    },
    openSource: {
      title: 'Open Source',
      content:
        'Artificial University is an open-source project. You can view the source code, report issues, or contribute to development on GitHub.',
      viewOnGitHub: 'View on GitHub',
    },
    creator: {
      title: 'About the Creator',
      bio: 'Artificial-U is created and maintained by me, Bennie Rosas. I write music and software in Minneapolis. I graduated from The Evergreen State College. Contact me at',
      outro:
        'I built this as a fun experiment, designed to spark joy and curiosity. I hope you enjoy it too. Reach out to share your thoughts.',
    },
    exploreCourses: 'Explore Courses',
  },

  // Common UI elements
  common: {
    loading: 'Loading...',
    error: 'Error',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    close: 'Close',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    viewAll: 'View All',
    previous: 'Previous',
    retry: 'Retry',
    refresh: 'Refresh',
    saving: 'Saving...',
    deleting: 'Deleting...',
    generating: 'Generating...',
    uploading: 'Uploading...',
    exporting: 'Exporting...',
    cancelling: 'Cancelling...',
    adding: 'Adding...',
    unknownError: 'Unknown error',
    notProvided: 'Not provided',
    noDescription: 'No description available.',
    nA: 'N/A',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    page: 'Page',
    of: 'of',
    ascending: 'Ascending',
    descending: 'Descending',
  },

  // Academics page
  academics: {
    title: 'Academics',
    faculties: 'Faculties',
    departments: 'Departments',
    seeAllDepartments: 'see all departments',
    loadingFaculties: 'Loading faculties...',
    loadingDepartments: 'Loading departments...',
    errorLoadingFaculties: 'Error loading faculties',
    errorLoadingDepartments: 'Error loading departments',
    noFacultiesFound: 'No faculties found',
    noDepartmentsFound: 'No departments found for this faculty.',
  },

  // Courses page
  courses: {
    title: 'Academic Courses',
    addCourse: 'Add Course',
    createNewCourse: 'Create New Course',
    filterByDepartment: 'Filter by Department',
    allDepartments: 'All Departments',
    clearFilter: 'Clear filter',
    myCourses: 'My Courses',
    myCoursesOnly: 'My Courses Only',
    sortField: 'Sort field',
    sortBy: 'Sort by',
    order: 'Order',
    code: 'Code',
    courseTitle: 'Title',
    level: 'Level',
    lastUpdate: 'Last Update',
    created: 'Created',
    teacher: 'Teacher',
    department: 'Department',
    creator: 'Creator',
    audioFiles: 'Audio Files',
    audioCoverage: 'Audio Coverage',
    updated: 'Updated',
    viewCourse: 'View course →',
    loading: 'Loading courses...',
    errorLoading: 'Error loading courses',
    noCoursesFound: 'No courses found',
    courseCreationFailed: 'Course creation failed',
    failedToEnqueue: 'Failed to enqueue course creation',
  },

  // Professors page
  professors: {
    title: 'Professors',
    addProfessor: 'Add Professor',
    createNewProfessor: 'Create New Professor',
    searchPlaceholder: 'Search professors...',
    allFaculties: 'All Faculties',
    allDepartments: 'All Departments',
    loadingFaculties: 'Loading faculties...',
    loadingDepartments: 'Loading departments...',
    loading: 'Loading professors...',
    errorLoading: 'Error loading professors',
    noProfessorsFound: 'No professors found',
    failedToCreate: 'Failed to create professor',
  },

  // Departments page
  departments: {
    title: 'Departments',
    addDepartment: 'Add Department',
    createNewDepartment: 'Create New Department',
    searchPlaceholder: 'Search departments...',
    allFaculties: 'All Faculties',
    loadingFaculties: 'Loading faculties...',
    loading: 'Loading departments...',
    errorLoading: 'Error loading departments',
    noDepartmentsFound: 'No departments found',
    failedToCreate: 'Failed to create department',
  },

  // Profile page
  profile: {
    title: 'My Profile',
    loading: 'Loading profile...',
    name: 'Name',
    email: 'Email',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully!',
    failedToLoad: 'Failed to load profile',
    failedToUpdate: 'Failed to update profile',
    enrollmentStatus: 'Enrollment Status',
    status: 'Status',
    coinBalance: 'Coin Balance',
    coins: 'coins',
    accountInformation: 'Account Information',
    accountId: 'Account ID',
    authId: 'Auth ID',
    accountActive: 'Account Active',
    roles: {
      viewer: 'Audit Only',
      creator: 'Enrolled',
      admin: 'Admin',
    },
  },

  // Admin Dashboard
  admin: {
    title: 'Admin Dashboard',
    filterByRole: 'Filter by Role',
    allRoles: 'All Roles',
    role: 'Role',
    viewer: 'Viewer',
    creator: 'Creator',
    admin: 'Admin',
    active: 'Active',
    inactive: 'Inactive',
    amount: 'Amount',
    addCoins: 'Add Coins',
    roleUpdated: 'Role updated successfully for student',
    failedToUpdateRole: 'Failed to update role',
    pleaseEnterValidCoins: 'Please enter a valid positive number of coins',
    addedCoins: 'Added',
    coinsToStudent: 'coins to student',
    failedToAddCoins: 'Failed to add coins',
    errorLoading: 'Error loading students',
    unknownError: 'Unknown error',
  },

  // Jobs page
  jobs: {
    title: 'Background Jobs',
    all: 'All',
    queued: 'Queued',
    running: 'Running',
    done: 'Done',
    failed: 'Failed',
    cancelled: 'Cancelled',
    cancel: 'Cancel',
    cancelJob: 'Cancel Job',
    confirmCancel: 'Are you sure you want to cancel this job?',
    failedToCancel: 'Failed to cancel job. Please try again.',
    noErrorAvailable: 'No error message available',
    errorLoading: 'Error loading jobs',
  },

  // Course Detail page
  courseDetail: {
    department: 'Department',
    professor: 'Professor',
    loadingDepartment: 'Loading department...',
    loadingProfessor: 'Loading professor...',
    departmentNotAvailable: 'Department info not available.',
    professorNotAvailable: 'Professor info not available.',
    faculty: 'Faculty',
    topics: 'Topics',
    lectures: 'Lectures',
    noTopicsFound: 'No topics found in this course.',
    noLecturesFound: 'No lectures found in this topic.',
    loadingTopics: 'Loading topics...',
    loadingLectures: 'Loading lectures...',
    errorLoadingTopics: 'Error loading topics',
    errorLoadingLectures: 'Error loading lectures',
    playAudio: 'Play lecture audio',
    downloadAudio: 'Download lecture audio',
    openDetail: 'Open lecture detail',
    editCourse: 'Edit Course',
    deleteCourse: 'Delete Course',
    export: 'Export',
    exporting: 'Exporting...',
    deleting: 'Deleting...',
    failedToUpdate: 'Failed to update course',
    failedToDelete: 'Failed to delete course',
    failedToExport: 'Failed to export course',
    level: 'Level',
    credits: 'Credits',
    noTopicsDefined: 'No topics defined for this course.',
    generatingTopics: 'Generating course topics...',
    week: 'Week',
    topic: 'Topic',
    lecture: 'Lecture',
    invalidCourseId: 'Invalid Course ID.',
    loadingCourse: 'Loading course details...',
    courseNotFound: 'Course not found.',
    backToCourses: 'Back to Courses',
    publishing: 'Publishing...',
    publishCourse: 'Publish Course',
    failedToPublish: 'Failed to publish course',
    exportJobEnqueued: 'Export job enqueued. Check the Jobs page for status.',
    viewJobStatus: 'View job status',
    confirmDeletion: 'Confirm Deletion',
    confirmDeleteMessage:
      'Are you sure you want to delete this course? This action cannot be undone.',
    published: 'Published',
    hidden: 'Hidden',
    courseDetails: 'Course Details',
    courseTopics: 'Course Topics',
    lecturesPerWeek: 'Lectures per week',
    totalWeeks: 'Total weeks',
    editTopics: 'Edit Topics',
    topicGenerationInProgress:
      'Topic generation in progress. The page will update automatically when complete.',
  },

  // Department Detail page
  departmentDetail: {
    courses: 'Courses',
    professors: 'Professors',
    loadingCourses: 'Loading courses...',
    loadingProfessors: 'Loading professors...',
    errorLoadingCourses: 'Error loading courses',
    errorLoadingProfessors: 'Error loading professors',
    noCoursesFound: 'No courses found in this department.',
    noProfessorsFound: 'No professors found in this department.',
    editDepartment: 'Edit Department',
    deleteDepartment: 'Delete Department',
    failedToLoad: 'Failed to load department',
    failedToUpdate: 'Failed to update department',
    failedToDelete: 'Failed to delete department',
    invalidDepartmentId: 'Invalid department ID',
    level: 'Level',
    credits: 'Credits',
  },

  // Lecture Detail page
  lectureDetail: {
    generatingAudio: 'Generating Audio...',
    regenerateAudio: 'Regenerate Audio',
    generateAudio: 'Generate Audio',
    uploadAudio: 'Upload Audio',
    uploading: 'Uploading...',
    delete: 'Delete',
    deleting: 'Deleting...',
    deleteLecture: 'Delete Lecture',
    confirmDelete: 'Delete',
    failedToUpdate: 'Failed to update lecture',
    failedToDelete: 'Failed to delete lecture',
    failedToGenerateAudio: 'Failed to generate audio',
    pleaseSelectAudioFile: 'Please select an audio file (MP3 recommended)',
    fileSizeLimit: 'File size must be less than 50MB',
    failedToUploadAudio: 'Failed to upload audio',
    errorLoading: 'Failed to load lecture',
  },

  // Theme Switcher
  theme: {
    selectTheme: 'Select Theme',
    description: 'Choose an aesthetic that matches your scholarly pursuits.',
    darkAcademia: 'Dark Academia',
    darkAcademiaDesc: 'Classical elegance with a scholarly aesthetic',
    vaporwave: 'Vaporwave',
    vaporwaveDesc: 'Retro-futuristic digital aesthetics',
    wabiSabi: 'Wabi Sabi',
    wabiSabiDesc: 'Embracing imperfection and natural simplicity',
    biophilia: 'Biophilia',
    biophiliaDesc: 'Lush greens, floral pops, and natural textures',
    changeTheme: 'Change theme',
    currentTheme: 'Current theme',
  },

  // Quickstart Wizard
  quickstart: {
    // Access control
    creatorAccessRequired: 'Creator Access Required',
    creatorPrivilegesNeeded: 'The Quickstart feature requires creator privileges.',

    // Step labels
    steps: {
      intent: 'Intent',
      professor: 'Professor',
      complete: 'Complete',
    },

    // Error messages
    errors: {
      failedToCreateCourse: 'Failed to create course. Please try again.',
      failedToFinalize: 'Failed to finalize course. Please try again.',
      failedToSearch: 'Failed to search for courses. Please try again.',
      failedToGenerateVoice: 'Failed to generate voice preview',
      failedToRegenerateImage: 'Failed to regenerate image',
      failedToReassignVoice: 'Failed to reassign voice',
      failedToRegenerateProfessor: 'Failed to regenerate professor',
    },

    // Common actions
    startOver: 'Start Over',

    // Complete step
    courseCreated: 'Course Created!',
    courseBeingPrepared: "Your course is being prepared. You'll be redirected shortly...",

    // Intent step
    intent: {
      title: 'What would you like to learn?',
      subtitle: "Describe your learning goal and we'll create a personalized course for you.",
      placeholder:
        'e.g., I want to understand machine learning fundamentals, including supervised and unsupervised learning algorithms...',
      hint: 'Be as specific as you like - the more detail, the better we can tailor your course.',
      searching: 'Searching...',
      creatingCourse: 'Creating Course...',
      startLearning: 'Start Learning',
      coursesFound: 'We found some courses for you!',
      listenNow: 'Listen Now',
      wantSomethingDifferent: 'Want something different?',
      buildSomethingNew: 'Build Something New',
      creating: 'Creating...',
    },

    // Professor step
    professor: {
      title: 'Meet Your Instructor',
      guideThroughCourse: 'This professor will guide you through',
      teachingStyle: 'Teaching style:',
      hearTheirVoice: 'Hear Their Voice',
      generating: 'Generating...',
      or: 'or',
      sampleVoice: 'Sample Voice',
      useThisTeacher: 'Use This Teacher',
      creatingCourse: 'Creating Course...',
      regenerate: 'Regenerate',
      changeSomething: 'Change Something',
      image: 'Image',
      voice: 'Voice',
      details: 'Details',

      // Image regeneration
      generateNewPortrait: 'Generate a new portrait for',
      regenerateImage: 'Regenerate Image',
      regenerating: 'Regenerating...',

      // Voice reassignment
      assignDifferentVoice: 'Assign a different voice to',
      reassignVoice: 'Reassign Voice',
      assigning: 'Assigning...',

      // Professor regeneration
      describeProfessorPreference: "Describe what kind of professor you'd prefer:",
      professorPromptPlaceholder:
        'e.g., A professor with industry experience, more focus on practical applications, younger and more energetic...',
      generateNewProfessor: 'Generate New Professor',
    },
  },
}

export type Locale = typeof en
