overrides:
  '@typescript-eslint/utils': ^8.70.1
  '@typescript-eslint/typescript-estree': ^8.70.1

allowBuilds:
  '@biomejs/biome': true
  '@tailwindcss/oxide': true
  browser-tabs-lock: true
  esbuild: true

pmOnFail: ignore
trustLockfile: true
