overrides:
  '@typescript-eslint/utils': ^8.59.0
  '@typescript-eslint/typescript-estree': ^8.59.0

allowBuilds:
  '@biomejs/biome': true
  '@tailwindcss/oxide': true
  browser-tabs-lock: true
  esbuild: true

pmOnFail: ignore
trustLockfile: true
